# You can replace the keys here directly if you don't to set env vars
model_list:
  - model_name: anthropic/claude-sonnet-4-20250514
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic/claude-opus-4-1-20250805
    litellm_params:
      model: anthropic/claude-opus-4-1-20250805
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: gemini/gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: gemini/gemini-2.5-pro-preview-03-25
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-03-25
      api_key: os.environ/GOOGLE_API_KEY
  - model_name: xai/grok-4-0709
    litellm_params:
      model: xai/grok-4-0709
      api_key: os.environ/XAI_API_KEY
  - model_name: openai/gpt-5
    litellm_params:
      model: openai/gpt-5
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai/gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY


